version: '3'

services:

  postgres:
    image: postgres:12.4
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      default:
        aliases:
          - postgres


  botserver:
    container_name: botserver
    env_file: .env
    build: app
    restart: always
    command: sh -c 'cd app && python manage.py runserver 0.0.0.0:8000'
    volumes:
        - .:/dockyard
    environment:
      - DEV_MODE=False
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - BOT_TOKEN=${BOT_TOKEN}

    ports:
      - 8000:8000
    links:
      - postgres



